# Generated by Django 5.2 on 2025-04-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пицца'},
        ),
    ]
