# Generated by Django 5.2 on 2025-04-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_logs', '0002_alter_pizza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы'},
        ),
    ]
